/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conf;

import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.font.TextAttribute;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author student
 */
public class InternalFrame extends javax.swing.JInternalFrame 
{
    FeedArticle data;
    public InternalFrame() 
    {
        initComponents();
    }

    InternalFrame(String article) 
    {
        initComponents();
        //this.setTitle(article);
    }
    
    public InternalFrame(FeedArticle data)
    {
        initComponents();
        this.data=data;
        //showData();
    }
    
    public final void showData()
    {
        titleLabel.setText(data.title);
        contentLabel.setText("<html>"+data.description+"</html>");
        linkLabel.setText(data.link);
    }
    
    class rsv extends MouseAdapter
    {
        public void mouseEntered(MouseEvent evt)
                        {
                            Savebutton.setVisible(true);
                            Mailbutton.setVisible(true);
                            Delbutton.setVisible(true);
                            
                    
                        }
                        public void mouseExited(MouseEvent evt)
                        {
                            Savebutton.setVisible(false);
                            Mailbutton.setVisible(false);
                            Delbutton.setVisible(false);
                           
                        } 
                        public void mouseClick(MouseEvent evt)
                        {
                            Savebutton.setVisible(true);
                            Mailbutton.setVisible(true);
                            Delbutton.setVisible(true);
                        }
                        public void mousePressed(MouseEvent evt)
                        {
                            Savebutton.setVisible(true);
                            Mailbutton.setVisible(true);
                            Delbutton.setVisible(true);
                        }
                        
                        public void mouseReleased(MouseEvent evt)
                        {
                            Savebutton.setVisible(true);
                            Mailbutton.setVisible(true);
                            Delbutton.setVisible(true);
                        }
    }
    
    
    public void test()
    {
                    Savebutton.setVisible(false);
                    Mailbutton.setVisible(false);
                    Delbutton.setVisible(false);
           //hover
                    rsv Handler=new rsv();
                    this.addMouseListener(Handler);
                
                     Delbutton.addMouseListener(Handler);
                     Savebutton.addMouseListener(Handler);
                     Mailbutton.addMouseListener(Handler);
                     //jLabel1.setText("Article");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Savebutton = new javax.swing.JButton();
        Mailbutton = new javax.swing.JButton();
        Delbutton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        contentLabel = new javax.swing.JLabel();
        linkLabel = new javax.swing.JLabel();

        Savebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Conf/save.png"))); // NOI18N
        Savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebuttonActionPerformed(evt);
            }
        });

        Mailbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Conf/email.png"))); // NOI18N
        Mailbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailbuttonActionPerformed(evt);
            }
        });

        Delbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Conf/del.png"))); // NOI18N
        Delbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelbuttonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleLabel.setText("Article Title");

        contentLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contentLabel.setText("Article");

        linkLabel.setForeground(new java.awt.Color(0, 0, 153));
        linkLabel.setText("Link");
        linkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                linkLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 407, Short.MAX_VALUE)
                .addComponent(Savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mailbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkLabel)
                    .addComponent(contentLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Mailbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Savebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(contentLabel)
                .addGap(29, 29, 29)
                .addComponent(linkLabel)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebuttonActionPerformed
        String content = contentLabel.getText();
        String title = titleLabel.getText();
        String link = linkLabel.getText();
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("txt", "TXT");
        fileChooser.setFileFilter(filter);
        if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) 
        {
            
         
            File file = fileChooser.getSelectedFile();
            
            BufferedWriter writer = null;
try
{
    writer = new BufferedWriter( new FileWriter(file.getAbsolutePath()));
    writer.write(title);
    writer.newLine();
    writer.write(content);
    writer.newLine();
    writer.write(link);
    

}
catch ( IOException e)
{
}
finally
{
    try
    {
        if ( writer != null)
        writer.close( );
    }
    catch ( IOException e)
    {
    }
}
        }     
    }//GEN-LAST:event_SavebuttonActionPerformed

    private void MailbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailbuttonActionPerformed

    private void DelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelbuttonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_DelbuttonActionPerformed

    private void linkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabelMouseClicked
        String k = linkLabel.getText();
        URL url = null;
        try {
            url = new URL(k);
        }
        catch(MalformedURLException e)
        {
            e.printStackTrace();
        }
        
        openWebpage(url);
    }//GEN-LAST:event_linkLabelMouseClicked

    private void linkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabelMouseEntered
        Font font;
        font = linkLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        linkLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_linkLabelMouseEntered

    private void linkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabelMouseExited
        Font font;
        font = linkLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        linkLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_linkLabelMouseExited

    private void linkLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkLabelMousePressed
        Font font;
        font = linkLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        linkLabel.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_linkLabelMousePressed
     
    
    public static void openWebpage(URI uri) {
    Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
    if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
        try {
            desktop.browse(uri);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
    
    public static void openWebpage(URL url) {
    try {
        openWebpage(url.toURI());
    } catch (URISyntaxException e) {
        e.printStackTrace();
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Delbutton;
    public javax.swing.JButton Mailbutton;
    public javax.swing.JButton Savebutton;
    public javax.swing.JLabel contentLabel;
    private javax.swing.JLabel linkLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
