/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Conf;
import Conf.MainFrame.*;
import static Conf.Settings.jButton1;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
/**
 *
 * @author Ravi Vasista
 */
public class Splash extends javax.swing.JFrame 
{
    public static String one = "Gathering the feeds";
    public static String two = "Parsing the XML files";
    public static String three = "       Finalizing";
    public static String four = "       Let's begin!";
    public static String k[] = new String[100];
    public static ImageIcon loading = new ImageIcon("431.gif");
    public static ImageIcon logo = new ImageIcon("Logo90.png");                                                                                                                                                                                                                                                                                                                                                                                                                             
    
    

    /**
     * Creates new form NewJFrame2
     */
    public Splash() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel(logo);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel(loading);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Neuropol", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confluence");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Conf/400.gif"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(256, 256));
        jLabel3.setMinimumSize(new java.awt.Dimension(256, 256));
        jLabel3.setPreferredSize(new java.awt.Dimension(256, 256));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {                                                                                             
                Splash l = new Splash();
                l.setVisible(true);
                l.getContentPane().setBackground(Color.BLACK);
                
                
                
                
                ActionListener actionListener;
                actionListener = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                      
                        
                        jLabel2.setText(one);
                        
                        
                    }
                };
                javax.swing.Timer timer = new javax.swing.Timer(5000, actionListener);
                timer.start();
                timer.setRepeats(false);
                
                ActionListener actionListener2;
                actionListener2 = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                        
                        jLabel2.setText(two);
                        
                        
                    }
                };
                javax.swing.Timer timer2 = new javax.swing.Timer(10000, actionListener2);
                timer2.start();
                timer2.setRepeats(false);
                
                ActionListener actionListener3;
                actionListener = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                        
                        jLabel2.setText(three);
                        
                        
                    }
                };
                javax.swing.Timer timer3 = new javax.swing.Timer(15000, actionListener);
                timer3.start();
                timer3.setRepeats(false);
                
                ActionListener actionListener4;
                actionListener = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                        
                        jLabel2.setText(four);
                        
                        
                    }
                };
                javax.swing.Timer timer4 = new javax.swing.Timer(20000, actionListener);
                timer4.start();
                timer4.setRepeats(false);
                
                ActionListener actionListener5;
                actionListener5 = new ActionListener() {
                    public void actionPerformed(ActionEvent actionEvent) {
                        
                       
                        
                    }
                };
                javax.swing.Timer timer5 = new javax.swing.Timer(25000, actionListener5);
                timer5.start();
                timer5.setRepeats(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
